# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'templatesRepository'
    subscriptionId: '3b17d851-4b89-4b9f-b4f4-99ccab0432be'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'dev-template-test-rg'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/whitechapel5991/MangoRestarauntDeploymentTemplates/main/mangoRestaurantTemplate.json'
    overrideParameters: |
      -administratorLogin "dshcharbakou"               
      -administratorLoginPassword "7752393LoL!"
      -productApiDbServerName "mango-service-productapidbserver1"
      -sqlDBName "Mango.Service.ProductAPI2_db"
      -serverfarmsMangoPlanName "mango-plan"
      -sitesMangoProductApiDevName "mango-ProductApi-dev2"
    deploymentMode: 'Incremental'
    deploymentName: 'DeployMangoTemplates'